/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.jewelleryEnterprise.gold;

import java.awt.CardLayout;
import java.awt.Image;
import javax.imageio.ImageIO;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.EcoSystem;
import model.enterprise.Enterprise;
import model.organization.Organization;
import model.userAccount.UserAccount;
import model.workQueue.WorkRequest;

/**
 *
 * @author lenovo
 */
public class GoldDashboardJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    UserAccount account;
    Organization organization;
    Enterprise enterprise;
    EcoSystem system;
//    Image imgLogo;
    
    public GoldDashboardJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
//        imgLogo.setIcon(ImageIO.read(getClass().getResource("../resources/logo.png")));
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        lblWelcome.setText("Welcome "+ account.getUsername());
        populateTable();
    }
    public void populateTable(){
        
        DefaultTableModel model = (DefaultTableModel) tblGoldDashboard.getModel();
        model.setRowCount(0);

        for (WorkRequest wr : account.getWorkQueue().getWorkRequestList()) {
            Object row[] = new Object[6];
            
            row[0] = wr;
            row[1] = wr.getReceiver();
            row[2] = wr.getMessage();
            row[3] = wr.getStatus();
            row[4] = wr.getRequestDate();
            row[5] = wr.getResolveDate();
            
            model.addRow(row);
        
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        btnLoanGold = new javax.swing.JButton();
        btnBuyGold = new javax.swing.JButton();
        btnRepairGold = new javax.swing.JButton();
        btnSellGold = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGoldDashboard = new javax.swing.JTable();

        setBackground(new java.awt.Color(222, 181, 126));

        btnLogout.setBackground(new java.awt.Color(64, 52, 36));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(64, 52, 36));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome Username");

        btnLoanGold.setBackground(new java.awt.Color(64, 52, 36));
        btnLoanGold.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLoanGold.setForeground(new java.awt.Color(255, 255, 255));
        btnLoanGold.setText("Loan Gold");
        btnLoanGold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoanGoldActionPerformed(evt);
            }
        });

        btnBuyGold.setBackground(new java.awt.Color(64, 52, 36));
        btnBuyGold.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuyGold.setForeground(new java.awt.Color(255, 255, 255));
        btnBuyGold.setText("Buy Gold");
        btnBuyGold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyGoldActionPerformed(evt);
            }
        });

        btnRepairGold.setBackground(new java.awt.Color(64, 52, 36));
        btnRepairGold.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRepairGold.setForeground(new java.awt.Color(255, 255, 255));
        btnRepairGold.setText("Repair Gold");
        btnRepairGold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepairGoldActionPerformed(evt);
            }
        });

        btnSellGold.setBackground(new java.awt.Color(64, 52, 36));
        btnSellGold.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSellGold.setForeground(new java.awt.Color(255, 255, 255));
        btnSellGold.setText("Sell Gold");
        btnSellGold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellGoldActionPerformed(evt);
            }
        });

        tblGoldDashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "From", "To", "Message", "Status", "Request Date", "Resolve Date"
            }
        ));
        tblGoldDashboard.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblGoldDashboard);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(456, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnBuyGold, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSellGold, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(btnRepairGold, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(btnLoanGold, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                            .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(456, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRepairGold, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoanGold, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSellGold, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuyGold, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoanGoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoanGoldActionPerformed
        // TODO add your handling code here:
        LoanGoldJPanel lgjp = new LoanGoldJPanel(userProcessContainer,account,organization,enterprise, system);
        userProcessContainer.add("LoanGoldJPanel", lgjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnLoanGoldActionPerformed

    private void btnBuyGoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyGoldActionPerformed
        // TODO add your handling code here:4
        
        BuyGoldJPanel bgjp = new BuyGoldJPanel(userProcessContainer,account,organization,enterprise, system);
        userProcessContainer.add("BuyGoldJPanel", bgjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnBuyGoldActionPerformed

    private void btnSellGoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellGoldActionPerformed
        // TODO add your handling code here:
        SellGoldJPanel sgjp = new SellGoldJPanel(userProcessContainer,account,organization,enterprise, system);
        userProcessContainer.add("BuyGoldJPanel", sgjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSellGoldActionPerformed

    private void btnRepairGoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepairGoldActionPerformed
        // TODO add your handling code here:
        RepairGoldJPanel rgjp = new RepairGoldJPanel(userProcessContainer,account,organization,enterprise, system);
        userProcessContainer.add("RepairGoldJPanel", rgjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRepairGoldActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuyGold;
    private javax.swing.JButton btnLoanGold;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRepairGold;
    private javax.swing.JButton btnSellGold;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTable tblGoldDashboard;
    // End of variables declaration//GEN-END:variables
}
