/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.jewelleryEnterprise.gold;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import model.EcoSystem;
import model.enterprise.Enterprise;
import model.organization.Organization;
import model.userAccount.UserAccount;
import ui.CreateCustomerJPanel;

/**
 *
 * @author lenovo
 */
public class LoanGoldJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoanGoldJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Organization organization;
    Enterprise enterprise;
    EcoSystem system;
    
    public LoanGoldJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblRepairGold = new javax.swing.JLabel();
        btnExistingCustomer = new javax.swing.JButton();
        btnNewCustomer = new javax.swing.JButton();

        setBackground(new java.awt.Color(222, 181, 126));

        btnBack.setBackground(new java.awt.Color(64, 52, 36));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblRepairGold.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblRepairGold.setForeground(new java.awt.Color(64, 52, 36));
        lblRepairGold.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRepairGold.setText("Loan Gold");

        btnExistingCustomer.setBackground(new java.awt.Color(64, 52, 36));
        btnExistingCustomer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExistingCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnExistingCustomer.setText("Existing Customer");
        btnExistingCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExistingCustomerActionPerformed(evt);
            }
        });

        btnNewCustomer.setBackground(new java.awt.Color(64, 52, 36));
        btnNewCustomer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNewCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnNewCustomer.setText("New Customer");
        btnNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(380, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExistingCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(381, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRepairGold, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnExistingCustomer, btnNewCustomer});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRepairGold)
                .addGap(18, 18, 18)
                .addComponent(btnExistingCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNewCustomer)
                .addContainerGap(319, Short.MAX_VALUE))
        );

        btnExistingCustomer.getAccessibleContext().setAccessibleName("");
        btnNewCustomer.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component [] componentArray = userProcessContainer.getComponents();
        Component c = componentArray[componentArray.length-1];
        GoldDashboardJPanel gdjp = (GoldDashboardJPanel) c;
        gdjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCustomerActionPerformed
        // TODO add your handling code here:
        CreateCustomerJPanel ccjp = new CreateCustomerJPanel(userProcessContainer,account,organization,enterprise, system);
        userProcessContainer.add("CreateCustomerJPanel", ccjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnNewCustomerActionPerformed

    private void btnExistingCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExistingCustomerActionPerformed
        // TODO add your handling code here:
        LoanGoldDashboardJPanel lgdjp = new LoanGoldDashboardJPanel(userProcessContainer,account,organization,enterprise, system);
        userProcessContainer.add("LoanGoldDashboardJPanel", lgdjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnExistingCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExistingCustomer;
    private javax.swing.JButton btnNewCustomer;
    private javax.swing.JLabel lblRepairGold;
    // End of variables declaration//GEN-END:variables
}
