/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.jewelleryEnterprise.silver;

import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.EcoSystem;
import model.enterprise.Enterprise;
import model.organization.Organization;
import model.userAccount.UserAccount;
import model.workQueue.WorkRequest;
import ui.jewelleryEnterprise.gold.BuyGoldJPanel;

/**
 *
 * @author lenovo
 */
public class SilverDashboardJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    UserAccount account;
    Organization organization;
    Enterprise enterprise;
    EcoSystem system;
    
    public SilverDashboardJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        lblWelcome.setText("Welcome "+ account.getUsername());
        populateTable();
    }
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblSilverDashboard.getModel();
        model.setRowCount(0);

        for (WorkRequest wr : account.getWorkQueue().getWorkRequestList()) {
            Object row[] = new Object[6];
            
            row[0] = wr;
            row[1] = wr.getReceiver();
            row[2] = wr.getMessage();
            row[3] = wr.getStatus();
            row[4] = wr.getRequestDate();
            row[5] = wr.getResolveDate();
            
            model.addRow(row);
        
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        btnRepairSilver = new javax.swing.JButton();
        btnSellSilver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSilverDashboard = new javax.swing.JTable();
        btnLogout = new javax.swing.JButton();

        setBackground(new java.awt.Color(222, 181, 126));

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(64, 52, 36));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome Username");

        btnRepairSilver.setBackground(new java.awt.Color(64, 52, 36));
        btnRepairSilver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRepairSilver.setForeground(new java.awt.Color(255, 255, 255));
        btnRepairSilver.setText("Repair Silver");
        btnRepairSilver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepairSilverActionPerformed(evt);
            }
        });

        btnSellSilver.setBackground(new java.awt.Color(64, 52, 36));
        btnSellSilver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSellSilver.setForeground(new java.awt.Color(255, 255, 255));
        btnSellSilver.setText("Sell Silver");
        btnSellSilver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellSilverActionPerformed(evt);
            }
        });

        tblSilverDashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "From", "To", "Message", "Status", "Request Date", "Resolve Date"
            }
        ));
        jScrollPane1.setViewportView(tblSilverDashboard);

        btnLogout.setBackground(new java.awt.Color(64, 52, 36));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSellSilver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRepairSilver))
                    .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWelcome)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRepairSilver)
                    .addComponent(btnSellSilver))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSellSilverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellSilverActionPerformed
        // TODO add your handling code here:
        SellSilverJPanel ssjp = new SellSilverJPanel(userProcessContainer,account,organization,enterprise, system);
        userProcessContainer.add("SellSilverJPanel", ssjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSellSilverActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRepairSilverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepairSilverActionPerformed
        // TODO add your handling code here:
        RepairSilverJPanel rsjp = new RepairSilverJPanel(userProcessContainer,account,organization,enterprise, system);
        userProcessContainer.add("RepairSilverJPanel", rsjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRepairSilverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRepairSilver;
    private javax.swing.JButton btnSellSilver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTable tblSilverDashboard;
    // End of variables declaration//GEN-END:variables
}
