/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.admin;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.EcoSystem;
import model.enterprise.Enterprise;
import model.network.Network;
import model.product.Gold;
import model.userAccount.UserAccount;

/**
 *
 * @author lenovo
 */
public class SystemAdminJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    UserAccount account;
    EcoSystem system;
    
    public SystemAdminJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = system;
        populateCombo();
        populateEnterpriseTable();
    }
    
    private void populateCombo() {
        comboBoxNetwork.removeAllItems();
        for (Network network: system.getNetworkList()){
            comboBoxNetwork.addItem(network.toString());
        }
    }
    
    private void populateEnterpriseTable() {
        String selectedNetworkString = (String) comboBoxNetwork.getSelectedItem();
        Network selectedNetwork = system.findNetwork(selectedNetworkString);
        if (selectedNetwork == null){
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblEnterprise.getModel();
        model.setRowCount(0);
        for (Enterprise enterprise : selectedNetwork.getEnterpriseDirectory().getEnterpriseList()) {
            Object row[] = new Object[1];
            row[0] = enterprise;
            model.addRow(row);
        }
    }
    
    private void populateEnterpriseTable(String keyword) {
        String selectedNetworkString = (String) comboBoxNetwork.getSelectedItem();
        Network selectedNetwork = system.findNetwork(selectedNetworkString);
        if (selectedNetwork == null){
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblEnterprise.getModel();
        model.setRowCount(0);
        for (Enterprise enterprise : selectedNetwork.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise.getName().contains(keyword)) {
                Object row[] = new Object[1];
                row[0] = enterprise;
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRepairGold = new javax.swing.JLabel();
        btnRemoveLocalAdmin = new javax.swing.JButton();
        btnSearchEnterprise = new javax.swing.JButton();
        txtSearchEnterprise = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();
        btnAddLocalAdmin = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLocalAdmins = new javax.swing.JTable();
        comboBoxNetwork = new javax.swing.JComboBox<>();
        lblGoldPrice = new javax.swing.JLabel();
        txtGoldPrice = new javax.swing.JTextField();
        btnSave = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(222, 181, 126));

        lblRepairGold.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblRepairGold.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRepairGold.setText("System Admin");

        btnRemoveLocalAdmin.setBackground(new java.awt.Color(64, 52, 36));
        btnRemoveLocalAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRemoveLocalAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveLocalAdmin.setText("Remove Admin");
        btnRemoveLocalAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveLocalAdminActionPerformed(evt);
            }
        });

        btnSearchEnterprise.setBackground(new java.awt.Color(64, 52, 36));
        btnSearchEnterprise.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearchEnterprise.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchEnterprise.setText("Search Enterprise");
        btnSearchEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchEnterpriseActionPerformed(evt);
            }
        });

        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Enterprise Name"
            }
        ));
        tblEnterprise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEnterpriseMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEnterprise);

        btnAddLocalAdmin.setBackground(new java.awt.Color(64, 52, 36));
        btnAddLocalAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddLocalAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAddLocalAdmin.setText("Add Admin");
        btnAddLocalAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLocalAdminActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(64, 52, 36));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        tblLocalAdmins.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Admin Name", "Role"
            }
        ));
        jScrollPane3.setViewportView(tblLocalAdmins);

        comboBoxNetwork.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxNetworkActionPerformed(evt);
            }
        });

        lblGoldPrice.setText("Set Gold Price :");

        btnSave.setBackground(new java.awt.Color(64, 52, 36));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel1.setText("Enterprise :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddLocalAdmin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRemoveLocalAdmin))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(comboBoxNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                    .addComponent(txtSearchEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnSearchEnterprise))
                                .addComponent(jScrollPane2)
                                .addComponent(jScrollPane3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblGoldPrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtGoldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSave)))
                        .addContainerGap(296, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRepairGold, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comboBoxNetwork, txtGoldPrice, txtSearchEnterprise});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRepairGold)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchEnterprise)
                    .addComponent(txtSearchEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddLocalAdmin)
                    .addComponent(btnRemoveLocalAdmin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGoldPrice)
                    .addComponent(txtGoldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave))
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveLocalAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveLocalAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveLocalAdminActionPerformed

    private void btnAddLocalAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLocalAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddLocalAdminActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void comboBoxNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxNetworkActionPerformed
        // TODO add your handling code here:
        populateEnterpriseTable();
    }//GEN-LAST:event_comboBoxNetworkActionPerformed

    private void btnSearchEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchEnterpriseActionPerformed
        // TODO add your handling code here:
        String keyword = txtSearchEnterprise.getText();
        if (keyword.isBlank()) {
            JOptionPane.showMessageDialog(this, "Search field cannot be blank.");
            return;
        }
        populateEnterpriseTable(keyword);
    }//GEN-LAST:event_btnSearchEnterpriseActionPerformed

    private void tblEnterpriseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEnterpriseMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblEnterprise.getSelectedRow();

        if (selectedRow < 0){
            return;
        }
        Enterprise enterprise = (Enterprise) tblEnterprise.getValueAt(selectedRow, 0);
        DefaultTableModel model = (DefaultTableModel) tblLocalAdmins.getModel();
        model.setRowCount(0);
        for (UserAccount userAccount: enterprise.getUserAccountDirectory().getUserAccounts()) {
            Object row[] = new Object[2];
            row[0] = userAccount;
            row[1] = userAccount.getRole().toString();
            model.addRow(row);
        }
    }//GEN-LAST:event_tblEnterpriseMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            Gold.changeGoldPrice(Double.parseDouble(txtGoldPrice.getText()));
            JOptionPane.showMessageDialog(this, "Gold Price Changed Successfully.");
            txtGoldPrice.setText("");
            return;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Enter a valid number.");
            return;
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLocalAdmin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRemoveLocalAdmin;
    private javax.swing.JToggleButton btnSave;
    private javax.swing.JButton btnSearchEnterprise;
    private javax.swing.JComboBox<String> comboBoxNetwork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblGoldPrice;
    private javax.swing.JLabel lblRepairGold;
    private javax.swing.JTable tblEnterprise;
    private javax.swing.JTable tblLocalAdmins;
    private javax.swing.JTextField txtGoldPrice;
    private javax.swing.JTextField txtSearchEnterprise;
    // End of variables declaration//GEN-END:variables
}
