/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.jewelleryEnterprise.billing;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.enterprise.Enterprise;
import model.order.Order;
import model.organization.Organization;
import model.organization.SecurityOrganization;
import model.userAccount.UserAccount;
import model.workQueue.WorkRequest;

/**
 *
 * @author lenovo
 */
public class BillingRoleHomeJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    UserAccount account;
    Organization organization;
    Enterprise enterprise;
    
    public BillingRoleHomeJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        lblWelcome.setText("Welcome "+ account.getUsername());
        populateTable();
        
    }
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblBilling.getModel();
        model.setRowCount(0);

        for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
            Object row[] = new Object[6];
            
            row[0] = wr;
            row[1] = wr.getReceiver();
            row[2] = wr.getMessage();
            row[3] = wr.getStatus();
            row[4] = wr.getRequestDate();
            row[5] = wr.getResolveDate();
            
            model.addRow(row);
        
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBilling = new javax.swing.JTable();
        btnCash = new javax.swing.JButton();
        btnOnlinePayment = new javax.swing.JButton();
        btnAssignToMe = new javax.swing.JButton();
        btnSendToSecurity = new javax.swing.JButton();

        setBackground(new java.awt.Color(222, 181, 126));

        btnLogout.setBackground(new java.awt.Color(64, 52, 36));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(64, 52, 36));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome Username");

        tblBilling.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "From", "To", "Message", "Status", "Request Date", "Resolve Date"
            }
        ));
        jScrollPane1.setViewportView(tblBilling);

        btnCash.setBackground(new java.awt.Color(64, 52, 36));
        btnCash.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCash.setForeground(new java.awt.Color(255, 255, 255));
        btnCash.setText("Cash Payment");
        btnCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashActionPerformed(evt);
            }
        });

        btnOnlinePayment.setBackground(new java.awt.Color(64, 52, 36));
        btnOnlinePayment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOnlinePayment.setForeground(new java.awt.Color(255, 255, 255));
        btnOnlinePayment.setText("Online Payment");
        btnOnlinePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnlinePaymentActionPerformed(evt);
            }
        });

        btnAssignToMe.setBackground(new java.awt.Color(64, 52, 36));
        btnAssignToMe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAssignToMe.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignToMe.setText("Assign to me");
        btnAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToMeActionPerformed(evt);
            }
        });

        btnSendToSecurity.setBackground(new java.awt.Color(64, 52, 36));
        btnSendToSecurity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSendToSecurity.setForeground(new java.awt.Color(255, 255, 255));
        btnSendToSecurity.setText("Send to Security");
        btnSendToSecurity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendToSecurityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCash)
                                .addGap(18, 18, 18)
                                .addComponent(btnOnlinePayment)
                                .addGap(18, 18, 18)
                                .addComponent(btnSendToSecurity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAssignToMe))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(114, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWelcome)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCash)
                    .addComponent(btnOnlinePayment)
                    .addComponent(btnAssignToMe)
                    .addComponent(btnSendToSecurity))
                .addContainerGap(227, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToMeActionPerformed
        // TODO add your handling code here:
        
        
        int selectedRow = tblBilling.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select work request first.");
            return;
        }

        WorkRequest request = (WorkRequest)tblBilling.getValueAt(selectedRow, 0);
        if (!request.getAssigned()) {
            request.setReceiver(account);
            request.setStatus("Pending");
            request.setAssigned(true);
            populateTable();
        } else {
            JOptionPane.showMessageDialog(this, "This work request is already assigned.");
            return;
        }
    }//GEN-LAST:event_btnAssignToMeActionPerformed

    private void btnCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashActionPerformed
        int selectedRow = tblBilling.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select work request first.");
            return;
        }
        
        WorkRequest request = (WorkRequest)tblBilling.getValueAt(selectedRow, 0);
        if (!request.getAssigned()) {
            JOptionPane.showMessageDialog(this, "Work request not assigned by you, so assign request first.");
            return;
        }
        request.setStatus("Paid in Cash");
        // find order and change status
        String message = request.getMessage();
        int id;
        id  = Integer.parseInt(message.substring(message.indexOf("$")+1));
        Order o = enterprise.getMasterOrderList().findOrder(id);
        o.setStatus("Paid in cash");

        populateTable();
        
        
    }//GEN-LAST:event_btnCashActionPerformed

    private void btnOnlinePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnlinePaymentActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblBilling.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select work request first.");
            return;
        }
        
        WorkRequest request = (WorkRequest)tblBilling.getValueAt(selectedRow, 0);
        if (!request.getAssigned()) {
            JOptionPane.showMessageDialog(this, "Work request not assigned by you, so assign request first.");
            return;
        }
        request.setStatus("Paid Online");
        // find order and change status
        String message = request.getMessage();
        int id;
        id  = Integer.parseInt(message.substring(message.indexOf("$")+1));
        Order o = enterprise.getMasterOrderList().findOrder(id);
        o.setStatus("Paid Online");

        populateTable();
    }//GEN-LAST:event_btnOnlinePaymentActionPerformed

    private void btnSendToSecurityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendToSecurityActionPerformed
        int selectedRow = tblBilling.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select work request first.");
            return;
        }
        
        WorkRequest request = (WorkRequest) tblBilling.getValueAt(selectedRow, 0);
        if (!request.getAssigned()) {
            JOptionPane.showMessageDialog(this, "Work request not assigned by you, so assign request first.");
            return;
        }
        if (request.getStatus().equals("Pending")) {
            JOptionPane.showMessageDialog(this, "Please mark payment before sending to security.");
            return;
        }
        request.setAssigned(false);
        Organization org = null;
        for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (o instanceof SecurityOrganization){
                org = o;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
        }

        populateTable();
    }//GEN-LAST:event_btnSendToSecurityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToMe;
    private javax.swing.JButton btnCash;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOnlinePayment;
    private javax.swing.JButton btnSendToSecurity;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTable tblBilling;
    // End of variables declaration//GEN-END:variables
}
